### ISSUE TITLE
Extend introduction, add overview and remove/edit notes

### ISSUE THREAD

**Issue by elear** [scionassociation/scion-cp_I-D#14]
>   \*Note:\* It is assumed that readers of this draft are familiar with
   the basic concepts of the SCION next-generation inter-domain network
   architecture.  If not, please find more detailed information in the
   IETF Internet Drafts [I-D.scion-overview], [I-D.scion-components],
   [I-D.scion-dp], and [I-D.scion-cppki], as well as in [CHUAT22],
   especially Chapter 2.  A short description of the SCION basic terms
   and elements can be found in Section 1.1 below.

the first two documents are not in my queue and I don't expect them.

Same issue in other drafts: 
- DP https://github.com/scionassociation/scion-dp_I-D/issues/10
- CPPKI https://github.com/scionassociation/scion-cppki_I-D/issues/29

**Comment by nicorusti** [comment]
- [ ] on the ISD definition, change language on jurisdiction (i.e. --> e.g.)
