### ISSUE TITLE
Clarifications about AS interfaces and peering

### ISSUE THREAD

**Issue by nicorusti** [scionassociation/scion-cp_I-D#17]
> From:	Joel Halpern 
> There is no description of how an A control service knows the existence of the many AS interfaces, whether they are core, up, down, or peering interfaces, and what AS they go to.

> There is also no information about how the needed properties of peering adjacencies are made available to the control service.

> Also, somewhere (not sure if it is a data plane or control plane mechanism), there needs to be a mechanism to translate neighbor interface identifiers to underlay addresses.

Most if this is pre-configured by the AS, in the OS implementation in the [topology file](https://docs.scion.org/en/latest/manuals/common.html#topology-json), we should indeed add something about this to the draft.

Also, Eliot commented about  peering ASe: We use the expression in the introduction. We say that peering links can cross ISDs. We need to define what is a peering AS (especially WRT to case outside an ISD). Important to make it clear that peering is possible across ISDs.

**Comment by jiceatscion** [comment]
I tried to address both points by I probably failed at least one. PTAL.
