### ISSUE TITLE
Clarify time synchronization dependency

### ISSUE THREAD

**Issue by nicorusti** [scionassociation/scion-cp_I-D#18]
What are the time synchronization dependencies between routers? Do you assume NTP? What happens if clocks drift?  Any dependencies must be listed. Maybe we could even have a section about dependencies. It is important as SCION is a such fundamentalc component that we must clearly list dependencies.. 

- [x] CLarify  routers requires syncronized time for path segments expiration (depending on lifetime on path segments, between 6m and one day, with 6m granularity).
- [x] There is a tolerance value for CP certificate verification. In SCIONLab this had to be extended where NTPs did not work. 
- [x] Add a reference to where lifetimes are specified (could be the DP draft)
- [x] Check if DP draft also needs to be updated
- [x] ~Certificate validation for gRPC calls: what is the tolerance and where is it specified~

**Comment by jiceatscion** [comment]
Addressed the question of clock drift in the dataplane with: https://github.com/scionassociation/scion-dp_I-D/pull/19

**Comment by jiceatscion** [comment]
Also copied the formula to interpret expTime from the DP draft.

**Comment by jiceatscion** [comment]
Not, that the time-tolerance for certificates is no-longer needed nor applied: Updated the cp draft to clarify that segments are not authenticated by certificates valid "now", but by certificates valid for the same period as the segment. Therefore current time during validation plays no role. Possibly a time offset between an AS's certificate originator and that of its core control service could play a role, but I think it's safe to assume that the can have the same time source.

**Comment by nicorusti** [comment]
Finally closing this after both CP & DP are updated. Thanks a lot @jiceatscion !
