### ISSUE TITLE
Anapaya review

### ISSUE THREAD

**Issue by nicorusti** [scionassociation/scion-cp_I-D#50]
Following the first wave of ISE feedback, we did quite some work, especially on the control plane draft:

Please review (sorted by urgency): 
- #63 
- 2.3.3.  Effects of Clock Inaccuracy
-  2.4.  Path Discovery Time and Scalability
-  5.  Security Considerations
- Control Service gRPC API (appendix)

Other pointers:
- [Changelog](https://github.com/scionassociation/scion-cp_I-D/releases/tag/draft-dekater-scion-controlplane-04)
- [Datatracker diff v-03 to main](https://author-tools.ietf.org/api/iddiff?doc_1=draft-dekater-scion-controlplane-03&url_2=https://scionassociation.github.io/scion-cp_I-D/draft-dekater-scion-controlplane.txt) 

@shitz @oncilla @sgmonroy could one of you have a look at the overall changes and provide some feedback? If you feel, you can  directly open a PR.  We are planning to have a new submission when datatracker reopens on 21.07, before our panrg session to address #48 , and it would be great if we could also incorporate some of your feedback.

**Comment by oncilla** [comment]
> The expiration of a SCION AS certificate typically ranges from	
 	   3h to 5 years.
 	   
 
Where does this number come from. Most typically it is 3days, and in some very special cases we have 5 days.
I have never seen 5 years outside of some private ISDs

**Comment by oncilla** [comment]
>  Once	
 	   this number grows above the maximum recommended best PCBs set size of	
 	   50, 
 	   
Where does this number come from? 
Default is 20. AFAIK:
https://github.com/scionproto/scion/blob/aa917bb458d6675efc55b4a23fda2c694094553e/control/beacon/policy.go#L43

**Comment by nicorusti** [comment]
> > The expiration of a SCION AS certificate typically ranges from
> > 3h to 5 years.
> 
> Where does this number come from. Most typically it is 3days, and in some very special cases we have 5 days. I have never seen 5 years outside of some private ISDs

This comes from https://github.com/scionassociation/scion-cp_I-D/commit/297e8d2c828228e22542cd27c6b708f29586a440  @jiceatscion do you have more background?

@oncilla you're right, in the PKI draft we write `The RECOMMENDED maximum validity period of a CP AS certificate is: 3 days.` I don't think, however, we set an upper bound to the validity. 

I see two action items: 

- [ ] Correct CP draft to say "3h to 5 _days_".
- [ ] Shall we set an upper bound for validity in the PKI draft? Or alternatively say that validity may be up to 5 days instead of 3?

**Comment by nicorusti** [comment]
The comes from the first version of the draft: https://github.com/scionassociation/scion-cp_I-D/commit/b652927759ca8f6c8767cc9e3ef44a71b0702f23

> > Once
> > this number grows above the maximum recommended best PCBs set size of
> > 50,
> 
> Where does this number come from? Default is 20. AFAIK: https://github.com/scionproto/scion/blob/aa917bb458d6675efc55b4a23fda2c694094553e/control/beacon/policy.go#L43

It comes from the initial version of the draft: 
https://github.com/scionassociation/scion-cp_I-D/commit/b652927759ca8f6c8767cc9e3ef44a71b0702f23
I could not find where this comes from

**Comment by jiceatscion** [comment]
> > Once
> > this number grows above the maximum recommended best PCBs set size of
> > 50,
> 
> Where does this number come from? Default is 20. AFAIK: https://github.com/scionproto/scion/blob/aa917bb458d6675efc55b4a23fda2c694094553e/control/beacon/policy.go#L43

These numbers aren't described as recommended values, but as recommended maxima. It came from some back-of-the-envelope calculations made by Matthias and used as worst-case examples in the scalability/Intra-ISD Beaconing section.

The code says the default is 20, but then, that isn't a recommended value, just a mechanical place holder: it is 20 even for the core policy, which, wouldn't be such a good idea, would it?

I'll try and clarify that notion in the text.

**Comment by jiceatscion** [comment]
> > The expiration of a SCION AS certificate typically ranges from
> > 3h to 5 years.
> 
> Where does this number come from. Most typically it is 3days, and in some very special cases we have 5 days. I have never seen 5 years outside of some private ISDs

I have no recollection. In all likeliness I was looking for the maximum range ever used and someone must have mentioned the existence the 5y case. If that is such an outlier, I can change the text to emphasize what the reasonable range is.

**Comment by jiceatscion** [comment]
> > > The expiration of a SCION AS certificate typically ranges from
> > > 3h to 5 years.
> > 
> > 
> > Where does this number come from. Most typically it is 3days, and in some very special cases we have 5 days. I have never seen 5 years outside of some private ISDs
> 
> This comes from [297e8d2](https://github.com/scionassociation/scion-cp_I-D/commit/297e8d2c828228e22542cd27c6b708f29586a440) @jiceatscion do you have more background?
> 
> @oncilla you're right, in the PKI draft we write `The RECOMMENDED maximum validity period of a CP AS certificate is: 3 days.` I don't think, however, we set an upper bound to the validity.
> 
> I see two action items:
> 
>     * [ ]  Correct CP draft to say "3h to 5 _days_".
> 
>     * [ ]  Shall we set an upper bound for validity in the PKI draft? Or alternatively say that validity may be up to 5 days instead of 3?

As usual, I can take a Jesuitic approach and make a distinction between common and recommended. That way we leave the pki draft and its recommendation of 3 days alone. In the cp draft I will made the same recommendation and mention 5 days as an outlier. Let's forget the 5y.
