### ISSUE TITLE
MTU clarifications

### ISSUE THREAD

**Issue by nicorusti** [scionassociation/scion-cp_I-D#57]
> Feedback Harald Alvestrand
> The description of SCION refers to using UDP/IP as the internal substrate inside an AS, and as a framing protocol on inter-AS links. This means that the Internet MTU of 1500 bytes (1200 for IPv6) will be in effect.
Path hops take 12 bytes + a couple of “segment headers” of 16 bytes - which means that a 10-hop, 3-segment path will take 168 bytes for the routing information. This is enough to reduce the MTU significantly, and the MTU will be unpredictable and maybe variable, since the path for a given packet may change dynamically.
(The packet format, like UDP’s, permits 68K-byte packets. However, fragmentation is A Thing.)

Also, I find this text is not clear: 
```
 mtu: The size of the maximum transmission unit (MTU) within the
      current AS's network.
```
Shoudln't this be the minimum MTU among alll intra-domain links in the AS (so the maximum supported MTU for intra-domain forwarding)? Maybe we can find a better wording

Related issues: 
* DP draft: https://github.com/scionassociation/scion-dp_I-D/issues/39
* Implementations: https://github.com/scionproto/scion/issues/2608

**Comment by jiceatscion** [comment]
Regarding MTUs in the control plane, I would suggest the following:

I would add a section 1.4.2.  Path Segments MTU, saying something like this: "Path segments represent a sequence of inter AS links, and intra-AS networks; each with possibly different MTUs. As a result, a path segment has an effective MTU which is the least of the MTUs of each link and intra-AS networks along the way."

In section 2.2.1.4.2 AS Entry Signed Body, describe the mtu field as follows: "The maximum transmission unit (MTU) that is supported by all hosts within the AS being described. This is set by the control service adding the entry to the beacon. How the control service obtains this information is implementation dependent. Current practice is do make it a configuration item."

In section 2.2.1.5 Hop Entry, describe the ingress_mtu field as follows: "Specifies the maximum transmission unit (MTU) of the ingress interface (in beaconing direction) of the hop being described. Packets traveling through the associated inter-AS link in either direction cannot exceed this size (not including the L2 header). As a result, no path segment constructed from the containing beacon can have an MTU greater than this. How the control service obtains the MTU of an inter-AS link is implementation depend. It may be discovered or configured. Current practice to make it a configuration item."

In section 2.2.1.7 Peer Entry, describe the peer_mtu field as follows: "Specifies the maximum transmission unit (MTU) of the peering link being described. Packets traveling through this link in either direction cannot exceed this size (not including the L2 header). As a result, no path segment constructed from the containing beacon can have an MTU greater than this. How the control service obtains the MTU of an inter-AS link is implementation depend. It may be discovered or configured. Current practice to make it a configuration item."

**Comment by nicorusti** [comment]
Great description, feel free to open a PR, and then I'd jsut do a bit of a wording pass. 

IN section  3.4. Paths MTU maybe you could add references to the various MTU fields (in  2.2.1.4.2 AS Entry Signed Body,  2.2.1.5 Hop Entry,  2.2.1.7 Peer Entry)

> the control service does not reduce the hop's MTU when that is the case. As a result, a scion host building a path must assume that all hops are constrained by the AS's internal network MTU. 

In this section, I'd refer to to current implementations rather than control service.

> not including the L2 header 

L2 --> Underlay/lower layer protocol

**Comment by nicorusti** [comment]
is the MTU directional? Does it affect path reversal (in terms of how endpoints calculate it)?

- [ ] Clarify this point in 4.4.  Path MTU
- [ ] Add a cross reference in 2.2.1.5.  Hop Entry pointing to 4.4.  Path MTU 

### Feedback Alvaro: 

```
...
1409	2.2.1.5.  Hop Entry
...
1439	   *  ingress_mtu: Specifies the maximum transmission unit (MTU) of the
1440	      ingress interface (in beaconing direction) of the hop being
1441	      described.  The MTU of paths constructed from the containing
1442	      beacon is necessarily less than or equal to this value.  How the
1443	      control service obtains the MTU of an inter-AS link is
1444	      implementation dependent.  It may be discovered or configured.
1445	      Current practice to make it a configuration item.

[] "in beaconing direction"
```

> Does this imply that the MTU in the opposite direction can be different?  If so, how is the reversible nature of the paths maintained?  Or is the reversible property only applicable to the fact that a path exists, and not that the characteristics are the same?

**Comment by jiceatscion** [comment]
Yeah, good point. I propose to clarify it along the following lines:

 "ingress interface MTU" means the MTU of that interface in both directions (which should be defined as the least of the MTU in either directions). It is the interface that is "ingress" not the MTU. The term "ingress interface in construction direction" is just a way to designate the interface relative to the path. Not the direction of traffic.
