### ISSUE TITLE
Write IANA Considerations Section

### ISSUE THREAD

**Issue by jiceatscion** [scionassociation/scion-cp_I-D#7]
See [RFC 8126](https://www.rfc-editor.org/rfc/rfc8126.html)

(Copied from https://github.com/scionassociation/standards/issues/100)

**Comment by jiceatscion** [comment]
For the control plane, there seems to be only two IANA consideration to address:
- Informational: The fact that SCION mirrors the UDP port space into the SCION/UDP port space. 
- The control service/discovery SCION/UDP port at 30252 which may need to become a reserved UDP/IP port as a consequence of the first point.
 
Everything else is AS-internal so requires no IANA arbitration.

Regarding port 30252, it is not even clear if that needs to be a reserved SCION/UDP port, given that it needs not be addressed directly but can be reached by way of a service address (and was once a dynamic port). As for port 30252 in to UDP/IP space, it is an AS-internal configuration anyway, so unless port 30252 needs to be reserved in the SCION/UDP space, it doesn't need to be reserved in the UDP/IP space.

On the other hand, Service Addresses themselves contain a hard-coded well-known number, so we might need to establish a registry for those. However, that would not be in the CP draft but may-be in the DP draft. Opinions welcome.

**Comment by jiceatscion** [comment]
Update: our internet drafts must not have any IANA actions so, for better or for worse we have to let everything be freely configurable. We might mention that "Informational: The fact that SCION mirrors the UDP port space into the SCION/UDP port space." as a justification for the absence of any IANA action requirement.

**Comment by nicorusti** [comment]
Hi @jceatscion in the draft we don't have the service discovery part (there was some discussion about this a while ago, and I think we removed it from the drafts, it might be in the old repo)

**Comment by nicorusti** [comment]
We discussed this with @jiceatscion and @matzf, port 30252 does not need to be reserved, this is an AS local configuration.
