### ISSUE TITLE
Make text representation of AS numbers more precise

### ISSUE THREAD

**Issue by nicorusti** [scionassociation/scion-cp_I-D#73]
We now have: 
```
The ISD-AS number is a SCION-specific number consisting of 64 bits: the top 16 bits indicating the ISD, and the bottom 48 bits indicating the AS. The text representation uses a dash separator between the ISD and AS numbers, e.g. `4-ff00:1:f`.
```

This should be integrated with details from  https://github.com/scionproto/scion/wiki/ISD-and-AS-numbering . We need this to be precise as this is referenced by the PKI draft in section "`ISD-AS number` Attribute", and it must coincide with the way the field is "printed" in the cert.

**Comment by jiceatscion** [comment]
What do you mean by "should be integrated"? Isn't the draft supposed to be authoritative? Both docs say the same thing, with the exception of how the decimal representation is supported: the draft says that the decimal representation is allowed for human consumption. The wiki says that programs always use it when talking to humans. Is that what the problem could be for PKI?

**Comment by nicorusti** [comment]
FOr the records, this is the text that I removed from the PKI draft ([PR](https://github.com/scionassociation/scion-cppki_I-D/pull/47)) to be replaced with a reference to the CP draft: 
```
- The canonical string representation uses a dash separator between the ISD and AS numbers.
- The ISD numbers are formatted as decimal.
- The canonical string formatting of AS numbers in the BGP AS range (0, 2<sup>32-1</sup>) is the decimal form. Larger AS numbers, i.e., from 2<sup>32</sup> to 2<sup>48-1</sup>, use a 16-bit, colon-separated, lower-case, hex encoding with leading zeros omitted: `1:0:0` to `ffff:ffff:ffff`.
```
