### ISSUE TITLE
Add section on scalability and convergence time

### ISSUE THREAD

**Issue by jiceatscion** [scionassociation/scion-cp_I-D#8]
Jeff Tantsura at our IETF117 presentation mentioned that it was not clear how SCION does in terms of convergence time. 
Then we also got this question from the iSE review: 

> From:	Joel Halpern
> There appears to be a very fundamental gap in the scaling description.  On the one hand, SCION claims to scale well (presumably to large numbers of participating AS.  There is no discussion of the effect of the number of participants or meshiness on the number of PCBs.  There are very strict limits on the rate at which PCBs are propagated.  But no analysis as to whether the system will ever converge .  Particularly if the number of interfaces between AS becomes large. 

Something about convergence time and scalability should be added to the draft. We could start from something like this:
> Note that, since there is no convergence phase in SCION, we cannot compare to BGP’s convergence time. SCION path-segments are stable as soon as they are disseminated.

Source:
https://netsec.ethz.ch/publications/papers/2021_conext_deployment.pdf

(Copied from https://github.com/scionassociation/standards/issues/82)

> From Roger Lapuh:  Explain why why 4030 ISDs is enough for public addressing. Refers to section 2.2.3 "Addressing > ISD Numbers"

> From Juan Garcia Pardo:  Where do the suggested values for set size and propagation time of PCBs in section 2.3.1.1. "Storing and Selecting Candidate PCBs" come from? Do they depend on the network topology? Explain.

**Comment by nicorusti** [comment]
Convergence time: 

- Clarify there is no convergence
- Time to bootstrap 
- Time to discover new link


Scalability: clarify tradeoffs
- Number of ISDs and core ASes
- Propagation intervals
- Number of AS entries
- meshyness of network

What is the cost metric: communication, storage, computation (e.g. signature verification)
